# Generated by Django 4.1.13 on 2024-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nouns', models.TextField()),
                ('verbs', models.TextField()),
            ],
        ),
    ]
