name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        working-directory: frontend/
        run: |
          npm install
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install backend dependencies
        working-directory: backend/
        run: |
          pip install -r requirements.txt
          pip install djongo==1.3.6
          pip install pymongo==3.12.1
          pip install mongoengine
          pip install dnspython
          pip install pytz

      - name: Run Django migrations
        working-directory: backend/
        run: |
          python manage.py makemigrations
          python manage.py migrate

      # - name: Collect static files for Django
      #   working-directory: backend/
      #   run: |
      #     python manage.py collectstatic

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: django-insecure-rkz9*=e&1av3d=(xmy*+apv%5@6vhl#*9hy%%gm)hjged2&9e9
      #     publish_dir: ./dist # Change this to your React build directory
      #     cname: menge.com # Optional: add a custom domain

      - name: Clean up
        run: |
          # Clean up any temporary files or configurations
